config/routes.rb
Rails.application.routes.draw do

  # namespace :admin do
  #   get 'tickets/create'
  #   get 'tqickets/update'
  #   get 'tickets/destroy'
  # end
  namespace :admin do
    resources :events
    resources :ticket_plans do
      resources :tickets
    end
    resources :movies
    resources :shows
    get '/', to: 'static#index'
  end

end

app/models/event.rb
class Event < ApplicationRecord

  validates :title, presence: true,
                    length: { in: 1..200}

  mount_uploader :image, PosterUploader

  
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController

    def index
      @id = params[:id]
      if params[:search]
        @events = Event.where("LOWER(title) LIKE :key_word OR
        LOWER(description) LIKE :key_word", {:key_word => "%#{params[:search].downcase}%"})
        .order(updated_at: :desc)
      else
        @events = Event.all.order(updated_at: :desc)
      end
      @regular_events, @cycle_events = [], []
      @events.each do |event|
        @cycle_events << event if event.is_cycle
        @regular_events << event if !event.is_cycle
      end
    end

    def update
      @event = Event.find(params[:id])
      @event.update(event_params)
      if @event.save
        flash[:success] = "Pomyślnie zmieniono"
        redirect_to :action => 'index', :id => @event.id
      else
        flash.now[:error] = "Błąd podczas edycji wydarzenia"
        render 'layouts/_flashTrigger'
      end
    end

    def create
      @event = Event.new(event_params)
      if @event.save
        flash[:success] = "Pomyślnie dodano"
        redirect_to :action => 'index', :id => @event.id
      else
        flash.now[:error] = "Błąd podczas dodawania wydarzenia"
        render 'layouts/_flashTrigger'
      end
    end

    def destroy
      @event = Event.find(params[:id])
      if @event.destroy
        flash[:success] = "Pomyślnie usunięto"
        id = nil
      else
        flash[:error] = "Błąd podczas usuwania wydarzenia"
        id = @event.id
      end
      redirect_to :action => 'index', :id => id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :description, :is_cycle, :image, :remove_image)
    end
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper

  def get_event_shows(event)
    Show.where(:event_id => event.id).order(start_time: :desc)
  end

end

app/views/admin/events/_blank_card.html.erb
<div class="card card-body border-bottom"><p class="text-center align-middle m-0">Brak Wydarzeń</p></div>

app/views/admin/events/_event.html.erb
  <div class="card event">
    <div class="card-header" id="eventHeader-<%=event.id%>" type="button" data-toggle="collapse" data-target="#eventContent-<%=event.id%>" aria-expanded="true" aria-controls="eventContent-<%=event.id%>">
      <div class="flex-row">
        <img class="img-thumbnail mr-3" src="<%=event.image.thumb.url%>"/>
        <h4 class="card-title vcenter m-0"><%= event.title %></h4>
      </div>
    </div>
    <div id="eventContent-<%=event.id%>" class="collapse accordion-card content eventContent" aria-labelledby="eventHeader-<%=event.id%>" data-parent="#eventAccordion">
      <div class="card-body">

        <div class="row">
          <div class="col-auto col-sm-4 col-lg-auto pb-3">
            <img class="card-img-left img-100" alt="Plakat" src="<%=(event.image.poster.url ? event.image.poster.url : image_path('noimage.png'))%>"/>
          </div>
          <div class="col col-sm-8 col-lg">
            <p class="text-justify" style="text-indent: 2rem"><%= event.description %></p>
          </div>
          <hr/>
        </div>

        <div class="card border-bottom">
          <div class="card-header">
            <div class="d-flex flex-row justify-content-between">
              <h5 class="card-title vcenter m-0 align-self-center">Projekcje w ramach wydarzenia</h5>
            </div>
          </div>
          <% unless get_event_shows(event).empty?  %>
            <div class="card-body">
              <ul class="list-group list-group-flush" id="event_shows-container-<%=event.id%>">
                <% get_event_shows(event).each do |show| %>
                  <li id="show<%=show.id%>" class="list-group-item">
                    <div class="row">
                      <p>
                        <b>Data: </b><%= show.start_time.strftime('%A, %e %B %Y') %>
                        <b>Godzina: </b><%= show.start_time.strftime('%k:%M') %>
                      </p>
                      <p><%= if movie = get_show_movie(show) then movie.title end%></p>
                    </div>
                  </li>
                <% end %>
              </ul>
            </div>
          <% else %>
            <%= render 'admin/shows/blank_card' %>
          <% end %>
        </div>

        <div class="row justify-content-end m-0 mt-3">
          <%= render 'eventModal', event: event, klass: "btn btn-outline-primary ml-2 mt-2 mt-sm-0"%>
          <%= button_to "Usuń", admin_event_path(event), method: 'delete', class: "btn btn-outline-danger flash-trigger ml-2 mt-2 mt-sm-0", data: { confirm: 'Na pewno?' } %>
        </div>
      </div>
    </div>
  </div>

app/views/admin/events/_eventModal.html.erb
<!-- Button trigger modal -->
<button type="button" class= "<%=klass%>" data-toggle="modal" data-target="#modal-<%= event ? event.id : "new"%>">
  <%= event ? "Edytuj" : "Nowe Wydarzenie"%>
</button>

<!-- Modal -->
<div class="modal fade img-inside" id="modal-<%= event ? event.id : "new"%>" tabindex="-1" role="dialog" aria-labelledby="v" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= event ? event.title : "Nowe Wydarzenie" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'form', event: event %>
    </div>
  </div>
</div>

app/views/admin/events/_form.html.erb
<%= form_with model: [:admin, event || event = Event.new], method: event.id ? "put" : "post", remote: true, :html => {id: "#{event.id}_form"} do |form| %>
<div class="modal-body row">

<div class="col-md-6">
  <div class="form-group">
    <%= form.select :is_cycle, { "Wydarzenie" => false, "Cykl" => true }, { }, { class: "form-control" } %>
  </div>

  <div class="form-group">
    <%= form.label "Tytuł:", class: "col-form-label-sm" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Opis:", class: "col-form-label-sm" %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
</div>

<div class="col-md-6">
  <div class="form-group">
    <label class="btn btn-outline-primary mr-1 mb-0 btn-sm">
      Dodaj plakat
      <%= form.file_field :image, onchange: "showImagePreview(this, #{event.id})", hidden: true %>
    </label>
    <button type="button" id="<%=event.id%>_imageRemover" class="btn btn-sm btn-outline-danger remover" onclick="removeImg(<%=event.id%>)"
      <%=if event.image.url.starts_with?("/assets/noimage") then 'disabled' end%> >Usuń plakat</button>
  </div>
  <img id="<%=event.id%>_imgPreview" class="col-12 img-resposive px-0"
       src= "<%= event.image.poster.url %>"
       alt= "Nie załączono plakatu"
       data-original= "<%= event.image.poster.url %>"/>
  <%= form.hidden_field :remove_image, :value => false, :id => "#{event.id}_remove_image"%>
</div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Anuluj</button>
  <%= form.submit "Zapisz", class: "btn btn-outline-primary flash-trigger" %>
</div>

<% end %>

app/views/admin/events/index.html.erb
<div class="card card-body">
  <div class="row d-flex justify-content-between align-items-center mx-1">
    <%= render 'eventModal', event: nil, klass: "btn btn-outline-primary mb-2 mb-md-0"%>
    <%= render 'layouts/search', url: "events" %>
  </div>
</div>
<div class="row mx-0">
  <div class="col-lg-6 px-0">
    <h3 class="my-3 pl-4">Wydarzenia:</h5>
    <div class="accordion" id="eventAccordion">
      <%= render @regular_events %>
    </div>
  </div>
  <div class="col-lg-6 px-0">
    <h3 class="my-3 pl-4">Cykle:</h5>
    <div class="accordion" id="eventAccordion">
      <%= render @cycle_events %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#eventContent-<%=@id%>").collapse('show')
</script>