config/routes.rb
Rails.application.routes.draw do

  # namespace :admin do
  #   get 'tickets/create'
  #   get 'tqickets/update'
  #   get 'tickets/destroy'
  # end
  namespace :admin do
    resources :events
    resources :ticket_plans do
      resources :tickets
    end
    resources :movies
    resources :shows
    get '/', to: 'static#index'
  end

end

app/models/show.rb
class Show < ApplicationRecord

  validates :start_time, presence: true
  validate :parent_exist
  validate :start_time_cannot_be_past

  def parent_exist
    unless movie_id || event_id
      errors.add(:movie_id, "Nie wybrano filmu lub wydarzenia do którego przypisanć projekcję")
    end
  end
  end

  def start_time_cannot_be_past
    unless start_time && start_time.future? do
      errors.add(:start_time, "must be ?future date")
    end
  end

  scope :before_next_friday, -> {
    where("start_time BETWEEN '#{DateTime.now.beginning_of_day}' AND '#{nearest_friday + 7}'")
  }

  private
  def nearest_friday
    day = Date.today
    until day.next_day.friday?
      day = day.next_day
    end
    day.next_day.to_datetime.beginning_of_day
  end

end

app/controllers/admin/shows_controller.rb
module Admin

  class ShowsController < Admin::ApplicationController
    include Admin::ShowsHelper

    def index
      @shows = Show.all
      @sorted_shows = get_sorted_future_shows(@shows)
    end

    def create
      @show = Show.new(show_params)
      if @show.save
        flash.now[:success] = 'Pomyślnie dodano projekcję'
        redirect_to :action => 'index', :id => @show.id
      else
        flash.now[:error] = 'Błąd podczas dodawania projekcji'
        render 'layouts/_flashTrigger'
      end
    end

    def update
      # @movie = Movie.find(params[:movie_id])
      @show = Show.find(params[:id])
      puts @show.inspect
      @show.update(show_params)
      if @show.save
        @movie.update_attribute(:updated_at, Time.now)
        flash.now[:success] = 'Pomyślnie zmieniono projekcję'
        redirect_to :action => 'index', :id => @show.id
      else
        flash.now[:error] = 'Błąd podczas edycji projekcji'
        render 'layouts/_flashTrigger'
      end
    end

    def destroy
      # @movie = Movie.find(params[:movie_id])
      @show = Show.find(params[:id])
      if @show.destroy
        flash.now[:success] = 'Pomyślnie usunięto projekcję'
      else
        flash.now[:error] = 'Błąd podczas usuwania projekcji'
      end
      redirect_to :action => 'index', :id => @show.id
    end

    private
    def show_params
      params.require(:show).permit(:start_time, :event_id, :ticket_plan_id, :movie_id)
    end

  end

end

app/helpers/admin/shows_helper.rb
module Admin::ShowsHelper

  def get_show_event(show)
    if show && show.event_id
      Event.find show.event_id
    end
  end

  def get_show_movie(show)
    if show && show.movie_id
      Movie.find show.movie_id
    end
  end

  def get_show_ticket_plan(show)
    if show && show.ticket_plan_id
      TicketPlan.find show.ticket_plan_id
    end
  end

  def get_show_parent(show)
    if show && show.movie_id
      Movie.find show.movie_id
    elsif show && show.event_id
      Event.find show.event_id
    end
  end

  def get_sorted_future_shows(shows)
    shows.select { |show| show.start_time.future? }
         .sort { |a, b| a.start_time - b.start_time }
  end
end

app/views/admin/shows/_blank_card.html.erb
<div class="card card-body border-bottom"><p class="text-center align-middle m-0">Brak Projekcji</p></div>

app/views/admin/shows/_form.html.erb
<%= form_with model: [:admin, show || show = Show.new], method: show.id ? "put" : "post", remote: true, :html => {id: "#{show.id}_show-form"} do |form| %>
  <div class="modal-body">
    <div class="form-group date">
      <div class="input-group datetimepicker" id="datetimepicker-<%=show.id%>" data-target-input="nearest">
        <%= form.text_field :start_time, { :class => "form-control datetimepicker-input", 'data-target' => "#datetimepicker-#{show.id}"}%>
        <div class="input-group-append" data-target="#datetimepicker-<%=show.id%>" data-toggle="datetimepicker">
          <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
      </div>
    </div>
    <div class="form-group">
      <%= form.label "Film:", class: "col-form-label-sm" %>
      <%= form.select :movie_id, Movie.all.collect {|movie| [ movie.title, movie.id ] }, { include_blank: true }, { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= form.label "Dodaj do wydarzenia:", class: "col-form-label-sm" %>
      <%= form.select :event_id, Event.all.collect {|event| [ event.title, event.id ] }, { include_blank: "Regularna projekcja" }, { class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= form.label "Plan taryfowy:", class: "col-form-label-sm" %>
      <%= form.select :ticket_plan_id, TicketPlan.all.collect {|ticket_plan| [ ticket_plan.name, ticket_plan.id ] }, { include_blank: "Wstęp wolny" }, { class: "form-control" } %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Anuluj</button>
    <%= form.submit "Zapisz", class: "btn btn-outline-primary"%>
  </div>
<% end %>

app/views/admin/shows/_show.html.erb
<div class="card" id="showCard-<%=show.id%>">
  <div class="card-header" id="showHeader-<%=show.id%>" type="button" data-toggle="collapse" data-target="#showContent-<%=show.id%>" aria-expanded="true" aria-controls="showContent-<%=show.id%>">
    <div class="row justify-content-between m-0">
      <h4 class="card-title vcenter m-0 p-0 align-self-center col-md-4">
        <%= show.start_time.strftime('%a, %e.%m, %k:%M')%>
      </h4>
      <h4 class="card-title vcenter m-0 p-0 align-self-center col-md-8 text-right">
        <%= get_show_parent(show).title %>
      </h4>
    </div>
  </div>
  <div id="showContent-<%=show.id%>" class="collapse accordion-card content showContent border-bottom" aria-labelledby="showHeader-<%=show.id%>" data-parent="#showAccordion">
    <div class="card-body pb-0">
      <p>
        <b>Data: </b><%= show.start_time.strftime('%A, %e %B %Y') %>
        <b>Godzina: </b><%= show.start_time.strftime('%k:%M') %>
      </p>
      <% if event = get_show_event(show) %><p><b>Wydarzenie / cykl: </b><%= event.title %></p><% end %>
      <%= render 'admin/ticket_plans/ticket_plan_inline', ticket_plan: get_show_ticket_plan(show) %>
    </div>
    <div class="row justify-content-end m-3">
      <%= render 'showModal', show: show, klass: "btn btn-outline-primary ml-2 mt-2 mt-sm-0"%>
      <%= button_to "Usuń", admin_show_path(show), method: 'delete', class: "btn btn-outline-danger flash-trigger ml-2 mt-2 mt-sm-0", data: { confirm: 'Na pewno?' } %>
    </div>
  </div>
</div>

app/views/admin/shows/_showModal.html.erb
<!-- Button trigger modal -->
<button type="button" class="<%= klass %>" data-toggle="modal" data-target="#showModal_<%= show ? show.id : "newShow"%>">
  <%= show ? "Edytuj" : "Nowa Projekcja" %>
</button>

<!-- Modal -->
<div class="modal fade show-modal" id="showModal_<%= show ? show.id : "newShow"%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= get_show_parent(show) ? get_show_parent(show).title : "Nowa Projekcja"%></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'admin/shows/form', show: show %>
    </div>
  </div>
</div>

app/views/admin/shows/_show_li.html.erb
<li id="show<%=show.id%>" class="list-group-item">
  <p>
    <b>Data: </b><%= show.start_time.strftime('%A, %e %B %Y') %>
    <b>Godzina: </b><%= show.start_time.strftime('%k:%M') %>
  </p>
  <% if get_show_parent(show).is_a?(Movie) && event = get_show_event(show) %>
    <p><b><%=event.title%></b></p>
  <% elsif get_show_parent(show).is_a?(Event) && movie = get_show_movie(show) %>
    <p><b><%=movie.title%></b></p>
  <% end %>

  <%= render 'admin/ticket_plans/ticket_plan_inline', ticket_plan: get_show_ticket_plan(show) %>
</li>

app/views/admin/shows/index.html.erb
<div class="card card-body">
<div class="row d-flex justify-content-between align-items-center mx-1">
  <%= render 'showModal', show: nil, klass: "btn btn-outline-primary mb-2 mb-md-0"%>
  <%= render 'layouts/search', url: "shows" %>
</div>
</div>
<div class="accordion" id="showAccordion">
  <%= unless @sorted_shows.empty? then render @sorted_shows else render 'blank_card' end%>
</div>
<script type="text/javascript">
  $("#showContent-<%=@id%>").collapse('show')
</script>