config/routes.rb
Rails.application.routes.draw do

  # namespace :admin do
  #   get 'tickets/create'
  #   get 'tqickets/update'
  #   get 'tickets/destroy'
  # end
  namespace :admin do
    resources :events
    resources :ticket_plans do
      resources :tickets
    end
    resources :movies
    resources :shows
    get '/', to: 'static#index'
  end

end

app/models/ticket.rb
class Ticket < ApplicationRecord
  
  belongs_to :ticket_plan

  validates :name, presence: true,
                    length: { in: 1..20}
end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < Admin::ApplicationController

  def create
    @ticket_plan = TicketPlan.find(params[:ticket_plan_id])
    @ticket = @ticket_plan.tickets.create(ticket_params)
    if @ticket.save
      @ticket = nil
      flash.now[:success] = 'Pomyślnie dodano'
      redirect_to :controller => 'ticket_plans', :action => 'index', :id => @ticket_plan.id
    else
      flash.now[:error] = 'Błąd podczas dodawania biletu'
      render 'layouts/_flashTrigger'
    end
  end

  def update
    @ticket_plan = TicketPlan.find(params[:ticket_plan_id])
    @ticket = Ticket.find(params[:id])
    if @ticket.save
      flash.now[:success] = 'Pomyślnie zmieniono'
      redirect_to :controller => 'ticket_plans', :action => 'index', :id => @ticket_plan.id
    else
      flash.now[:error] = 'Błąd podczas dodawania biletu'
      render 'layouts/_flashTrigger'
    end
  end

  def destroy
    @ticket_plan = TicketPlan.find(params[:ticket_plan_id])
    @ticket = Ticket.find(params[:id])
    if @ticket.destroy
      flash.now[:success] = 'Pomyślnie usunięto'
    else
      flash.now[:error] = 'Błąd podczas usuwania biletu'
    end
    redirect_to :controller => 'ticket_plans', :action => 'index', :id => @ticket_plan.id
  end

  private
  def ticket_params
    params.require(:ticket).permit(:name, :price)
  end
end

app/helpers/admin/tickets_helper.rb
module Admin::TicketsHelper
end

app/views/admin/tickets/_blank_card.html.erb
<div class="card card-body"><p class="text-center align-middle m-0">Brak Biletów</p></div>

app/views/admin/tickets/_form.html.erb
<%= form_with model: [:admin, ticket_plan, ticket || ticket = Ticket.new], method: ticket.id ? "put" : "post", remote: true, :html => {id: "#{ticket.id}ticket_form"} do |form| %>
  <div class="modal-body">
    <div class="row mx-2 p-0 justify-content-between">
      <%= form.text_field :name, class: "form-control col-8", placeholder: "Nazwa" %>
      <%= form.number_field :price, class: "form-control col-3", placeholder: "Cena" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Anuluj</button>
    <%= form.submit "Zapisz", class: "btn btn-outline-primary"%>
  </div>
<% end %>

app/views/admin/tickets/_ticket.html.erb
<li id="editTicket<%=ticket.id%>" class="list-group-item">
  <div class="row justify-content-between">
    <div class="col-md-8">
      <p><b><%= ticket.name %></b> <%= ticket.price %> zł</p>
    </div>
    <div class="col-md-4 flex-col justify-content-center">
      <div class="btn-toolbar justify-content-end">
        <%= render 'admin/tickets/ticket_modal', ticket_plan: ticket_plan, ticket: ticket, klass: "btn btn-outline-primary btn-sm", style: nil %>
        <%= button_to "Usuń", admin_ticket_plan_ticket_path(ticket_plan, ticket), method: 'delete', remote: true, class: "btn btn-outline-danger ml-2 flash-trigger btn-sm"%>
      </div>
    </div>
  </div>
</li>

app/views/admin/tickets/_ticket_modal.html.erb
<!-- Button trigger modal -->
<button type="button" class= "<%=klass%>" style="<%=style ? style : ""%>" data-toggle="modal" data-target="#ticket_modal-<%=ticket_plan.id%>-<%= ticket ? ticket.id : "new"%>">
  <%= ticket ? "Edytuj" : "Dodaj Bilet"%>
</button>

<!-- Modal -->
<div class="modal fade" id="ticket_modal-<%=ticket_plan.id%>-<%= ticket ? ticket.id : "new"%>" tabindex="-1" role="dialog" aria-labelledby="v" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"><%= ticket ? ticket.name : "Nowy Bilet" %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= render 'admin/tickets/form', ticket_plan: ticket_plan, ticket: ticket %>
    </div>
  </div>
</div>