config/routes.rb
Rails.application.routes.draw do

  # namespace :admin do
  #   get 'tickets/create'
  #   get 'tqickets/update'
  #   get 'tickets/destroy'
  # end
  namespace :admin do
    resources :events
    resources :ticket_plans do
      resources :tickets
    end
    resources :movies
    resources :shows
    get '/', to: 'static#index'
  end

end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> shadow">
    <script type="text/javascript"> setTimeout(function() { $(".alert").fadeOut(500) }, 2000) </script>
    <h4 class="alert-heading vcenter m-0"><%= value %></h4>
    <% if @movie && @movie.errors.any? %>
      <ul><% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%></ul>
    <%end%>
    <% if @show && @show.errors.any? %>
      <ul><% @show.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%end%></ul>
    <%end%>
  </div>
<% end %>

app/views/layouts/_flashTrigger.js.erb
document.getElementById("flash-place").innerHTML = "<%= escape_javascript (render partial: 'layouts/flash') %>"
setTimeout(function() { $(".alert").fadeOut(500) }, 2000)

app/views/layouts/_search.html.erb
<%= form_with url: url, local: true, method: "get", class: "form-inline justify-content-end" do |form| %>
    <%= form.text_field :search, value: params[:search] || '', class: "form-control mr-sm-2" %>
    <%= form.submit "Wyszukaj", class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paradox2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="flash-place">
      <%= render 'layouts/flash' %>
    </div>
    <div class="container">

      <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark">
        <%= link_to "Paradox", admin_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <%= active_link_to "Filmy", admin_movies_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
            <%= active_link_to "Wydarzenia i Cykle", admin_events_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
            <%= active_link_to "Projekcje", admin_shows_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
            <%= active_link_to "Plany Taryfowe", admin_ticket_plans_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
          </ul>
        </div>

      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paradox2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div id="flash-place">
      <%= render 'layouts/flash' %>
    </div>
    <div class="container">

      <nav class="navbar navbar-expand-md sticky-top navbar-dark bg-dark">
        <%= link_to "Paradox", admin_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <%= active_link_to "Filmy", admin_movies_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
            <%= active_link_to "Wydarzenia i Cykle", admin_events_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
            <%= active_link_to "Plany Taryfowe", admin_ticket_plans_path, class: 'nav-link', wrap_tag: :li, wrap_class: 'nav-item' %>
          </ul>
        </div>

      </nav>
      <%= yield %>
    </div>
  </body>
</html>